# Generated by Django 4.0.5 on 2022-07-10 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(help_text='Post ID', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Post title', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, default=' ')),
                ('updated', models.DateTimeField(auto_now=True, default=' ')),
                ('contents', models.TextField(help_text='post contents')),
                ('auth', models.ForeignKey(db_column='auth', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(help_text='Comment ID', primary_key=True, serialize=False)),
                ('contents', models.TextField(help_text='Comment contents')),
                ('post_id', models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.post')),
            ],
        ),
    ]
