# Generated by Django 4.0.5 on 2022-07-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kakao_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
