# Generated by Django 4.0.5 on 2022-07-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_kakao_id_alter_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kakao_id',
            field=models.IntegerField(max_length=50),
        ),
    ]
